


__version__ = "0.2021.11.20"



from .MediaWikiLocalSettingsArrayAppend import MediaWikiLocalSettingsArrayAppend
from .MediaWikiLocalSettingsComplexVariableAssignment import MediaWikiLocalSettingsComplexVariableAssignment
from .MediaWikiLocalSettingsVariableAssignment import MediaWikiLocalSettingsVariableAssignment
from .MediaWikiLocalSettingsFile import MediaWikiLocalSettingsFile



